# Generated by Django 4.2.10 on 2024-03-01 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_title', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='movie_poster')),
                ('description', models.CharField(max_length=255)),
                ('cast', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=3)),
                ('movie_type', models.CharField(max_length=30)),
                ('release_date', models.DateField(verbose_name='%d-%m-%Y')),
                ('duration', models.CharField(max_length=30)),
                ('rating', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('Show_Id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('Show_date', models.DateField(verbose_name='%d-%m-%Y')),
                ('Screen_No', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('screen_no', models.PositiveIntegerField()),
                ('booking_status', models.CharField(choices=[('BOOKED', 'BOOKED'), ('CANCELED', 'CANCELED')], default='CANCELED', max_length=24, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Show_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_movie.show')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('Theater_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=150)),
                ('total_screens', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='Theater_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Theater_show', to='book_movie.theater'),
        ),
        migrations.AddField(
            model_name='show',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_show', to='book_movie.movie'),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_row', models.CharField(max_length=1)),
                ('seat_col', models.PositiveIntegerField()),
                ('is_booked', models.BooleanField(default=False)),
                ('ticket_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_movie.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('ticket_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_movie.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
