# Generated by Django 4.2.10 on 2024-03-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='Screen_No',
            new_name='Screen_no',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Show_Id',
            new_name='Show_id',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='Show_Id',
            new_name='Show_id',
        ),
    ]
