# Generated by Django 4.2.10 on 2024-03-01 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_movie', '0002_rename_screen_no_show_screen_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='screen_no',
        ),
    ]
