# Generated by Django 4.2.10 on 2024-03-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_movie', '0003_remove_ticket_screen_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='ticket_price',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
