# Generated by Django 4.2.10 on 2024-03-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_movie', '0005_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_row',
            field=models.PositiveIntegerField(),
        ),
    ]
