# Generated by Django 4.2.10 on 2024-03-30 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_movie', '0009_alter_ticket_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='user_id',
        ),
    ]
