# Generated by Django 4.2.10 on 2024-03-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_movie', '0010_remove_rating_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.IntegerField()),
                ('order_id', models.CharField(blank=True, max_length=100)),
                ('razor_payment_id', models.CharField(blank=True, max_length=100)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
