# Generated by Django 4.2.10 on 2024-04-05 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_movie', '0011_razorpayment_delete_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theater',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theaters', to=settings.AUTH_USER_MODEL),
        ),
    ]
